# -*- coding: utf-8 -*-
"""Atharva Lecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoorybIr3li6GkfEYbIWK_uW-E9GGKN8
"""

#@title (FIRST DAY 3/4/2025)

print("Wel-Come to CompuTech Academy")

print("Hello")
print("How are You")
print("Kem Cho!")

a=10
print("Hello Atharva")
print("Your age is",a)

print(a)

print(a)

a=20

print(a)

a="Atharva"
b="St Aloysius High School"
c="Jigar Sir"

print("My name is",a,"MY School Name is",b,"My Teacher name is",c)

a=10
b=20
c=a+b
print(c)

d=c-10
print(d)

a=10
b=20
if a>b:
  print("A is Bigger")
else:
  print("B is Bigger")

a=int(input("Enter The First Number"))
b=int(input("Enter The Second Number"))

if a>b:
  print("A is Bigger")
else:
  print("B is Bigger")

a=input("Enter The Email ID")
b="jigar.pra42@gmail.com"
if b==a:
  print("valid")
else:
  print("InValid")

#@title 9/4/2025

a=int(input("Enter The Number"))
if a%2==0:
  print("Number is Even")
else:
  print("Number is Odd")

a=int(input("Enter The Marks of Hindi"))
b=int(input("Enter The Marks of English"))
c=int(input("Enter The Marks of Gujarati"))

d=a+b+c

print("Total Marks is",d)

e=d/300*100

print("Percentage is",e)

if e>=75:
  print("Oho! aap ko Dist aya")
elif e>=65 and e<75:
  print("Ouch! aapko A Grade aya")
elif e>=55 and e<65:
  print("Arere! Aap thode chuk gaye aapko B grade aya")
elif e>=45 and e<55:
  print("Kya hogaya he aapko, aapko to C Grade aya")
elif e>=35 and e<45:
  print("Arere! aapke mom ko call kar raha hu! Just D")
else:
  print("Ab to tumhari shamat!Tu fail ho gaya")

a=int(input("Enter The Sale Amount"))

if a>20000:
  b=a*5/100
  print("Your Incentive is",b)

#@title (10/4/2025)

x=int(input("Enter The Username"))
y=int(input("Enter The Password"))

if x==123 and y==123:
  print("Login!")

  abc=int(input("Enter The Number"))
  if abc>=10:
    print("Value is Bigger")
  else:
    print("Value is Lessor")

else:
  print("Login Fail")

  a=int(input("Enter The Number"))
  b=int(input("Enter The Number"))
  if a==b:
    print("Captcha Matched! Try again")
  else:
    print("Invalid Captcha")

bike=int(input("Enter The cost price of Bike"))

if bike>100000:
  b=bike*15/100
  print("Tax need to pay is",b)
elif bike>50000 and bike<100000:
  b=bike*10/100
  print("Tax need to pay is",b)
elif bike<50000:
  b=bike*5/100
  print("Tax need to pay is",b)
else:
  print("Wow! U have cycle")

bs=int(input("Enter the basic salary"))

if bs<1500:
  hra=bs*10/100
  da=bs*90/100

else:
  bs>=1500
  hra=500
  da=bs*98/100

gross=bs+hra+da
print("Your Gross salary is",gross)

#@title For Loop

for i in range(1,10):
  print(i)

for i in range(10,1,-1):
  print(i)

for i in range(1,10,2):
  print(i)

number=5

for i in range(1,10):
  print(number,'x',i,'=',number*i)

number=int(input("Enter Your Fav Table"))

for i in range(1,10):
  print(number,'x',i,'=',number*i)

number=int(input("Enter Your Fav Table"))
end=int(input("Enter The End Value"))

for i in range(1,end):
  print(number,'x',i,'=',number*i)

fact=1
for i in range(1,10):
  fact=fact*i
  print(fact)

for i in range(1,10):
  print(i,end='       ')

qty=int(input("Enter The value of Qty"))
price=float(input("Enter the Price"))

if qty>1000:
  dis=10
else:
  dis=0

total=(qty*price)-(qty*price*dis/100)
print(total)

bs=int(input("Enter the value of BS"))
if bs>1500:
  hra=bs*10/100
  da=bs*90/100
else:
  hra=500
  da=bs*98/100
gs=bs+da+hra
print("Gross salary=Rs."+str(gs))

ms=input("Enter the marital status:")
g=input("Enter the Gender")
age=int(input("Enter the age"))

if(ms=='m')or(ms=='u' and g=='m' and age>30)or(ms=='u' and g=='f' and age>25):
  print("Insured")
else:
  print("Not Insured")

#while loop

i=0
while i<=5:
  print(i)
  i=i+1

#while loop

i=10
while i>=1:
  print(i)
  i=i-1

num=5
i=1
while i<=10:
  print(num,"*",i,"=",num*i)
  i=i+1

num=int(input("Enter The Table"))
end=int(input("Enter The End Number"))
i=1
while i<end:
  print(num,"*",i,"=",num*i)
  i=i+1

fact=1
for i in range(1,10):
  fact=fact*i
  print(fact,end='     ')

fact=1
i=1
num=int(input("enter the number:"))
while i<=num:
  fact=fact*i
  print(fact,end='')
  i=i+1

i=1
while i<=3:
  p=float(input("Enter The Value of P"))
  n=int(input("Enter The Value of N"))
  r=float(input("Enter The Value of R"))
  si=p*n*r/100
  print("Simple Intrest - Rs",si)
  i=i+1

#@title 4/30/2025 (PYTHON LECTURE)
for alpha in range(97,122+1):
  print(chr(alpha),end=' ')

for alpha in range(122,97,-1):
  print(chr(alpha),end=' ')

for alpha in range(65,91):
  print(chr(alpha),end=' ')

for alpha in range(91,65,-1):
  print(chr(alpha),end=' ')

for i in range(3,4):
  for j in range(1,11):
    k=i*j
    print(i,"x",j,"=",k)

a=int(input("Enter The Table"))
for i in range(a,a+1):
  for j in range(1,11):
    k=i*j
    print(i,"x",j,"=",k)

for alpha in range(65,91):
  for alpha1 in range(97,122):
    print(chr(alpha1),end=' ')

a=int(input("Enter The Table"))

i=a
while i<=a:
  j=1
  while j<11:
    k=i*j
    print(i,"x",j,"=",k)
    j=j+1
  i=i+1